### ISSUE TITLE
Documentation warnings and error: Particle

### ISSUE THREAD

**Issue by Hendrik1704** [Hendrik1704/sparkx#161]
When we run `make clean && make html` in `docs/`, then there is one indentation error in the class docstring of `Particle`. I'm not able to find the mistake there, even after some hours of trying.

What I'm more concerned about is that there are many warnings after the recent changes in the class. This is something we should investigate.

**Comment by NGoetz** [comment]
I have tracked down the error using bisection to a7aa49caeb4b9ffc792c94e12ea6c3822a94396f . There seems to be some issue with the new way of reading in particles. 
Looking through our history, we actually had a lot of warnings coming and going. Maybe there should be also a GH action checking that there are no docu warnings when preparing a PR.

**Comment by NGoetz** [comment]
The warnings seem to come from 0a96b8f71e0088bb3c287d0dcc7faa2c1e6dc717. With this information, we should be able to tackle the issue tomorrow.

**Comment by Hendrik1704** [comment]
This is solved now
